AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Zucchini Secure Serveless API
Parameters:
  TagProjectParameter:
    Type: String
    Default: zucchini-default
    Description: Value to tag the Project tag key
Resources:
  GetFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: crud.get
      Runtime: nodejs4.3
      Policies: AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /resource/{resourceId}
            Method: get
    Tags: 
      Project:
        Ref: TagProjectParameter
  PutFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: crud.put
      Runtime: nodejs4.3
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
      Events:
        PutResource:
          Type: Api
          Properties:
            Path: /resource/{resourceId}
            Method: put
    Tags: 
      Project: !Ref TagProjectParameter
  DeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: crud.delete
      Runtime: nodejs4.3
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
      Events:
        DeleteResource:
          Type: Api
          Properties:
            Path: /resource/{resourceId}
            Method: delete
  Table:
    Type: AWS::Serverless::SimpleTable
    Tags: 
      Project: TagProjectParameterZucchini