AWSTemplateFormatVersion: '2010-09-09'
Description: Zucchini Secure Serveless API
Parameters:
  TagProjectParameter:
    Default: zucchini-default
    Description: Value to tag the Project tag key
    Type: String
Resources:
  DeleteFunction:
    Properties:
      CodeUri: s3://zucchini-deploy/898c9294decb041b4786a38a92efbc12
      Environment:
        Variables:
          TABLE_NAME:
            Ref: Table
      Events:
        DeleteResource:
          Properties:
            Method: delete
            Path: /resource/{resourceId}
          Type: Api
      Handler: crud.delete
      Policies: AmazonDynamoDBFullAccess
      Runtime: nodejs4.3
    Type: AWS::Serverless::Function
  GetFunction:
    Properties:
      CodeUri: s3://zucchini-deploy/898c9294decb041b4786a38a92efbc12
      Environment:
        Variables:
          TABLE_NAME:
            Ref: Table
      Events:
        GetResource:
          Properties:
            Method: get
            Path: /resource/{resourceId}
          Type: Api
      Handler: crud.get
      Policies: AmazonDynamoDBReadOnlyAccess
      Runtime: nodejs4.3
    Tags:
      Project:
        Ref: TagProjectParameter
    Type: AWS::Serverless::Function
  PutFunction:
    Properties:
      CodeUri: s3://zucchini-deploy/898c9294decb041b4786a38a92efbc12
      Environment:
        Variables:
          TABLE_NAME:
            Ref: Table
      Events:
        PutResource:
          Properties:
            Method: put
            Path: /resource/{resourceId}
          Type: Api
      Handler: crud.put
      Policies: AmazonDynamoDBFullAccess
      Runtime: nodejs4.3
    Tags:
      Project:
        Ref: TagProjectParameter
    Type: AWS::Serverless::Function
  Table:
    Tags:
      Project: TagProjectParameterZucchini
    Type: AWS::Serverless::SimpleTable
Transform: AWS::Serverless-2016-10-31
